version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL_SERVER1="mysql://u200603_cole:b.4tK5YBf3wX+0@68.168.213.248:3306/u200603_colegiados"
      - DATABASE_URL_SERVER2="mysql://u200603_u200603:b.4tK5YBf3wX+0@68.168.213.248:3306/u200603_croxcusco"
      - JWT_SECRET="secret"