version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL_SERVER1=${DATABASE_URL_SERVER1}
      - DATABASE_URL_SERVER2=${DATABASE_URL_SERVER2}
      - JWT_SECRET=${JWT_SECRET}